import random #Import random module

player_num = input("Угадай число от 1 до 10: ") #prompt the user to enter an integer from 1 to 10
num_1 = random.randint(1, 10) #we call the generation of numbers from 1 to 10
if player_num.isdigit():
    if player_num == num_1: #check the condition if the user named the number generated by the module
        print("You", player_num, "Computer", num_1, "\nYou Win!")#then print the numbers and congratulations
    else: #In other cases, we withdraw lost
        print("You", player_num, "Computer", num_1, "\nYou Lost!")
else:
    print("Not a digit")
